# Generated by Django 5.2.4 on 2025-07-29 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='mrn',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
    ]
